spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://deepamayavel68_db_user:J6BRHXQd6alT8rK6@cluster0.chu8att.mongodb.net/mediguide?retryWrites=true&w=majority&appName=Cluster0&serverSelectionTimeoutMS=5000&connectTimeoutMS=5000}
server.port=8080
jwt.secret=${JWT_SECRET:Y2hhbmdlLXRoaXMtc2VjcmV0LWNoYW5nZS10aGlzLXNlY3JldC0xMjM0NTY=}
jwt.expiry.short=86400000
jwt.expiry.long=604800000
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174
jena.endpoint=http://localhost:3030/mediguide/query
spring.jackson.serialization.write-dates-as-timestamps=false
spring.data.mongodb.auto-index-creation=false
